### ISSUE TITLE
Unable to build with io.js 2.2.1

### ISSUE THREAD

**Issue by jplock** [advertine/node-ip2location#1]
Hi, I'm unable to build this library with io.js 2.2.1.

```
[08:27:20][Step 1/3] > ip2location-native@1.0.5 install /home/teamcity/buildAgent/work/84a9308d6d94a72c/node_modules/ip2location-native
[08:27:20][Step 1/3] > node-gyp rebuild
[08:27:20][Step 1/3] 
[08:27:21][Step 1/3] make: Entering directory `/home/teamcity/buildAgent/work/84a9308d6d94a72c/node_modules/ip2location-native/build'
[08:27:21][Step 1/3]   CC(target) Release/obj.target/nodeip2location/src/curl/inet_pton.o
[08:27:21][Step 1/3]   CC(target) Release/obj.target/nodeip2location/src/ip2location/ip2lmemorymaplist.o
[08:27:21][Step 1/3]   CC(target) Release/obj.target/nodeip2location/src/ip2location/ip2lipaddress.o
[08:27:21][Step 1/3]   CC(target) Release/obj.target/nodeip2location/src/ip2location/ip2ldatabase.o
[08:27:21][Step 1/3]   CC(target) Release/obj.target/nodeip2location/src/ip2location/ip2location.o
[08:27:22][Step 1/3]   CXX(target) Release/obj.target/nodeip2location/src/nodeip2location.o
[08:27:22][Step 1/3] In file included from ../node_modules/nan/nan_new.h:190:0,
[08:27:22][Step 1/3]                  from ../node_modules/nan/nan.h:74,
[08:27:22][Step 1/3]                  from ../src/nodeip2location.h:4,
[08:27:22][Step 1/3]                  from ../src/nodeip2location.cc:1:
[08:27:22][Step 1/3] ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
[08:27:22][Step 1/3] ../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
[08:27:22][Step 1/3]    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
[08:27:22][Step 1/3]                                                                             ^
[08:27:22][Step 1/3] ../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
[08:27:22][Step 1/3] In file included from /home/teamcity/.node-gyp/2.2.1/src/node.h:42:0,
[08:27:22][Step 1/3]                  from ../node_modules/nan/nan.h:24,
[08:27:22][Step 1/3]                  from ../src/nodeip2location.h:4,
[08:27:22][Step 1/3]                  from ../src/nodeip2location.cc:1:
[08:27:22][Step 1/3] /home/teamcity/.node-gyp/2.2.1/deps/v8/include/v8.h:4188:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
[08:27:22][Step 1/3]    static Local<Signature> New(
[08:27:22][Step 1/3]                            ^
[08:27:22][Step 1/3] /home/teamcity/.node-gyp/2.2.1/deps/v8/include/v8.h:4188:27: note:   candidate expects 2 arguments, 4 provided
[08:27:22][Step 1/3] make: *** [Release/obj.target/nodeip2location/src/nodeip2location.o] Error 1
[08:27:22][Step 1/3] make: Leaving directory `/home/teamcity/buildAgent/work/84a9308d6d94a72c/node_modules/ip2location-native/build'
[08:27:22][Step 1/3] gyp ERR! build error 
[08:27:22][Step 1/3] gyp ERR! stack Error: `make` failed with exit code: 2
[08:27:22][Step 1/3] gyp ERR! stack     at ChildProcess.onExit (/home/teamcity/buildAgent/work/84a9308d6d94a72c/vendor/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
[08:27:22][Step 1/3] gyp ERR! stack     at emitTwo (events.js:87:13)
[08:27:22][Step 1/3] gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
[08:27:22][Step 1/3] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
[08:27:22][Step 1/3] gyp ERR! System Linux 3.8.0-44-generic
[08:27:22][Step 1/3] gyp ERR! command "/home/teamcity/buildAgent/work/84a9308d6d94a72c/vendor/bin/node" "/home/teamcity/buildAgent/work/84a9308d6d94a72c/vendor/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[08:27:22][Step 1/3] gyp ERR! cwd /home/teamcity/buildAgent/work/84a9308d6d94a72c/node_modules/ip2location-native
[08:27:22][Step 1/3] gyp ERR! node -v v2.2.1
[08:27:22][Step 1/3] gyp ERR! node-gyp -v v1.0.3
[08:27:22][Step 1/3] gyp ERR! not ok 
```

(the build is happening within TeamCity, but that shouldn't be an issue)

**Comment by royaltm** [comment]
looks like nan has a problem, I'll try to bump nan to 1.8

**Comment by royaltm** [comment]
it did help
I'll drop support for 0.8 it's breaking the ^ npm syntax and I don't think anyone will miss it

**Comment by royaltm** [comment]
please try 1.0.6
